### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by ibseq** [MigleSur/BacDist#4]
Hello
git clone doesn't work with link, so I downloaded the zip file but not sure how to install it?

thanks!
ibseq

**Comment by MigleSur** [comment]
Hello,

I am happy to hear that you find BacDist relevant for your work. Here are the instructions on how to clone the repository in GitHub: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository 

Best,
Migle
